# permissions for end users to edit namespaceclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: namespaceclass-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nsc-controller
    app.kubernetes.io/part-of: nsc-controller
    app.kubernetes.io/managed-by: kustomize
  name: namespaceclass-editor-role
rules:
- apiGroups:
  - akuity.io.my.domain
  resources:
  - namespaceclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akuity.io.my.domain
  resources:
  - namespaceclasses/status
  verbs:
  - get
