apiVersion: akuity.io.my.domain/v1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: namespaceclass
    app.kubernetes.io/instance: namespaceclass-sample
    app.kubernetes.io/part-of: nsc-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nsc-controller
  name: namespaceclass-sample
spec:
  # TODO(user): Add fields here
